### ISSUE TITLE
https://github.com/polarismesh/examples/tree/main/servicemesh/extended-bookinfo 链接错误

### ISSUE THREAD

**Issue by bartdong** [polarismesh/examples#5]
https://github.com/polarismesh/examples/tree/main/servicemesh/extended-bookinfo

Polaris Controller 已经安装完成，参考Polaris 网格使用指南
链接应指向为：https://github.com/polarismesh/website/blob/main/docs/zh/doc/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/%E4%BD%BF%E7%94%A8%E6%9C%8D%E5%8A%A1%E7%BD%91%E6%A0%BC.md

**Comment by zhangzerui20** [comment]
fixed in pr #7
